// WTJ-20260704-074 — static delivery check for pre-generated TTS audio.
// Asserts every missing-audio.json entry marked status:"delivered" for the three TTS
// categories (secretWords / taskVoice / compositePhrases) has a real, non-empty .m4a
// on disk at the declared path. This is the "静态检查" gate (acceptance criterion 7):
// it fails loudly if a delivered path is missing/empty or a count regresses, so a
// packaging step or a future edit can't silently drop audio the app expects to play.
//
// WTJ-20260704-084 update: added the same static delivery gate for the new ZH task-voice
// category (taskVoiceZh, 24 complete Chinese sentences — Kokoro zf_xiaoxiao). This is a
// distinct, additive count: the original EN gate is tracked separately (regenerated 084's
// EN audio byte-for-byte identical to the 074/075 delivery — see TTS-PROVENANCE.md), so
// this file still separately asserts the current EN counts to catch any future regression,
// plus the new 24-count ZH gate below.
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, existsSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const REPO = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const APP_WEB = join(REPO, 'app', 'web');
const manifest = JSON.parse(readFileSync(join(APP_WEB, 'audio', 'missing-audio.json'), 'utf8'));

function deliveredPaths(entries, pathKey) {
  return entries.filter((e) => e.status === 'delivered').map((e) => e[pathKey]);
}

const words = deliveredPaths(manifest.secretWords, 'path');
const tasks = deliveredPaths(manifest.taskVoice, 'voicePromptPath');
const phrases = deliveredPaths(manifest.compositePhrases, 'path');
const tasksZh = deliveredPaths(manifest.taskVoiceZh, 'voicePromptPath');

test('074+015+008: expected delivered TTS counts (100 words delivered incl. fox / 8 tasks / 10 phrases)', () => {
  // WTJ-20260706-011/015: xylophone/xray removed; fox integrated. WTJ-20260706-008: the
  // CosyVoice3 rework (ASR-gated reseed) produced a real fox.m4a (whisper-verified "Fox"),
  // so fox is now delivered — no longer pending, not faked with xray.
  assert.equal(words.length, 100, '100 secret word audio files delivered (incl. fox via 008 ASR-gated rework)');
  assert.equal(tasks.length, 8, 'all 8 task prompts delivered');
  assert.equal(phrases.length, 10, 'all 10 composite phrases delivered');
});

test('011+015+008: xylophone/xray removed and fox audio delivered via CosyVoice3 rework', () => {
  assert.equal(manifest.secretWords.some((e) => e.word === 'xylophone'), false, 'xylophone entry must not remain in missing-audio.json secretWords[]');
  assert.equal(manifest.secretWords.some((e) => e.word === 'xray'), false, 'xray entry must not remain in missing-audio.json secretWords[]');
  const fox = manifest.secretWords.find((e) => e.word === 'fox');
  assert.ok(fox, 'fox entry must exist in missing-audio.json secretWords[]');
  assert.equal(fox.status, 'delivered', 'fox.m4a delivered by WTJ-20260706-008 ASR-gated CosyVoice3 rework (real, whisper-verified file)');
});

test('084+024: expected delivered ZH task-voice count (32: 24 + 025 new 8)', () => {
  assert.equal(tasksZh.length, 32, 'all 32 ZH task sentences delivered (24 + WTJ-025 new 8, regenerated by WTJ-024 CosyVoice3)');
});

test('074: every delivered TTS .m4a exists on disk and is non-empty', () => {
  const missing = [];
  const empty = [];
  for (const rel of [...words, ...tasks, ...phrases]) {
    const abs = join(APP_WEB, rel);
    if (!existsSync(abs)) { missing.push(rel); continue; }
    if (statSync(abs).size === 0) empty.push(rel);
  }
  assert.deepEqual(missing, [], `missing audio files: ${missing.join(', ')}`);
  assert.deepEqual(empty, [], `empty (0-byte) audio files: ${empty.join(', ')}`);
});

test('084: every delivered ZH .m4a exists on disk and is non-empty', () => {
  const missing = [];
  const empty = [];
  for (const rel of tasksZh) {
    const abs = join(APP_WEB, rel);
    if (!existsSync(abs)) { missing.push(rel); continue; }
    if (statSync(abs).size === 0) empty.push(rel);
  }
  assert.deepEqual(missing, [], `missing ZH audio files: ${missing.join(', ')}`);
  assert.deepEqual(empty, [], `empty (0-byte) ZH audio files: ${empty.join(', ')}`);
});

test('074: delivered paths follow the audio/{words,tasks,phrases}/<name>.m4a convention', () => {
  for (const rel of words) assert.match(rel, /^audio\/words\/[^/]+\.m4a$/, rel);
  for (const rel of tasks) assert.match(rel, /^audio\/tasks\/[^/]+\.m4a$/, rel);
  for (const rel of phrases) assert.match(rel, /^audio\/phrases\/[^/]+\.m4a$/, rel);
});

test('084: delivered ZH paths follow the audio/tasks/<id>.zh.m4a convention (no collision with EN)', () => {
  const enTaskPaths = new Set(tasks);
  for (const rel of tasksZh) {
    assert.match(rel, /^audio\/tasks\/[^/]+\.zh\.m4a$/, rel);
    assert.equal(enTaskPaths.has(rel), false, `ZH path must not collide with an EN taskVoice path: ${rel}`);
  }
});

// =====================================================================================
// WTJ-20260706-011 — ZH secret-word audio delivery. FULL 100/100 delivered via the 008-approved
// CosyVoice3 ASR-gated reseed pipeline (generate-tts-asr-gated.py): every clip whisper-verified
// to read the target ZH word (reseed on miss; toneless-pinyin homophone rescue + opencc
// Traditional→Simplified normalization). The prior 85/100 pass left 15 short/single-char words
// pending; the rework delivered all 15 (single-char words that whisper transcribed as empty or a
// homophone got a child-friendly longer label, e.g. 猫→小猫 / 鱼→小鱼 / 岛→小岛, filename unchanged).
// 0 remain not-delivered; there is NO EN-fallback placeholder. Status ⟺ disk: delivered ⟺ a
// non-empty .m4a exists.
// =====================================================================================

const secretWordsZh = manifest.secretWordsZh;
const deliveredZh = secretWordsZh.filter((e) => e.status === 'delivered');
const notDeliveredZh = secretWordsZh.filter((e) => e.status === 'not-delivered');

test('011+008: secretWordsZh well-formed — 100 entries (100 delivered, 0 pending), one per pool word', () => {
  assert.equal(Array.isArray(secretWordsZh), true, 'missing-audio.json must have a secretWordsZh array');
  assert.equal(secretWordsZh.length, 100, 'secretWordsZh must have exactly 100 entries (one per current 100-word pool)');

  const enWordSet = new Set(manifest.secretWords.map((e) => e.word));
  const zhWordSet = new Set(secretWordsZh.map((e) => e.word));
  assert.equal(zhWordSet.size, 100, 'secretWordsZh words must be unique (no duplicates)');
  assert.deepEqual([...zhWordSet].sort(), [...enWordSet].sort(),
    'secretWordsZh word set must exactly match the EN secretWords word set (same 100 words, no drift)');

  for (const e of secretWordsZh) {
    assert.ok(e.status === 'delivered' || e.status === 'not-delivered', `${e.word}: status must be delivered|not-delivered`);
    assert.equal(typeof e.zhLabel, 'string', `${e.word}: zhLabel must be a string`);
    assert.ok(e.zhLabel.length > 0, `${e.word}: zhLabel must not be empty`);
    assert.equal(e.path, `audio/words/${e.word}.zh.m4a`, `${e.word}: path must follow the audio/words/<word>.zh.m4a convention`);
  }
  assert.equal(deliveredZh.length, 100, 'WTJ-20260706-011 返工: 100/100 ZH word audio delivered (008 ASR-gated CosyVoice3 pipeline)');
  assert.equal(notDeliveredZh.length, 0, '0 ZH words remain pending — 无 EN fallback 占位，全部中文已交付');
});

test('011+008: delivered secretWordsZh .m4a exist & non-empty; not-delivered do not exist (status ⟺ disk)', () => {
  for (const e of deliveredZh) {
    const abs = join(APP_WEB, e.path);
    assert.ok(existsSync(abs), `delivered ZH word audio must exist on disk: ${e.path}`);
    assert.ok(statSync(abs).size > 0, `delivered ZH word audio must be non-empty: ${e.path}`);
  }
  for (const e of notDeliveredZh) {
    assert.equal(existsSync(join(APP_WEB, e.path)), false, `not-delivered ZH path must not exist on disk yet: ${e.path}`);
  }
});

test('011+008: ZH delivery does not regress the EN secretWords 100-count gate (separate category)', () => {
  assert.equal(words.length, 100, 'the pre-existing EN secretWords delivered-count gate must remain 100 (untouched by the secretWordsZh category)');
});

test('011: app/scripts/tts-text-manifest.zh.json "words" segment matches missing-audio.json secretWordsZh 1:1 (same word set, same out path, same text/zhLabel)', () => {
  const zhManifestPath = join(REPO, 'app', 'scripts', 'tts-text-manifest.zh.json');
  const zhManifest = JSON.parse(readFileSync(zhManifestPath, 'utf8'));
  const zhWords = zhManifest.words;
  assert.equal(typeof zhWords, 'object', 'tts-text-manifest.zh.json must have a top-level "words" object');
  assert.equal(Object.keys(zhWords).length, 100, 'tts-text-manifest.zh.json words segment must have exactly 100 entries');

  for (const e of secretWordsZh) {
    const entry = zhWords[e.word];
    assert.ok(entry, `tts-text-manifest.zh.json words segment missing entry for "${e.word}"`);
    assert.equal(entry.out, e.path, `${e.word}: tts-text-manifest.zh.json out must match missing-audio.json secretWordsZh path`);
    assert.equal(entry.text, e.zhLabel, `${e.word}: tts-text-manifest.zh.json text must match missing-audio.json zhLabel (single source of truth for the ZH label)`);
    assert.match(entry.out, /^audio\/words\/[^/]+\.zh\.m4a$/, `${e.word}: out must follow the audio/words/<word>.zh.m4a convention`);
  }
});

test('011: summary.secretWordsZh block reports total=100, totalNotDelivered=0 (100/100 delivered by 008 ASR-gated CosyVoice3 pipeline)', () => {
  const summary = manifest.summary.secretWordsZh;
  assert.ok(summary, 'missing-audio.json summary.secretWordsZh block must exist');
  assert.equal(summary.total, 100);
  assert.equal(summary.totalNotDelivered, notDeliveredZh.length, 'summary.totalNotDelivered must match the actual count of not-delivered secretWordsZh entries');
  assert.equal(summary.totalNotDelivered, 0, 'WTJ-20260706-011 返工: 0 ZH words pending — 全部 100 中文已交付');
});
